### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by joywet** [tylerni7/missile-tid#32]
Traceback (most recent call last):
  File "/home/kavita/env/missile-tid-main/demos/vandenberg.py", line 58, in <module>
    sc = scenario.Scenario.from_daterange(date, 1 * util.DAYS, ca_stations, dog)
  File "/home/kavita/env/lib/python3.9/site-packages/tid-0.1.0-py3.9.egg/tid/scenario.py", line 173, in from_daterange
    locs, data = get_data.parallel_populate_data(
  File "/home/kavita/env/lib/python3.9/site-packages/tid-0.1.0-py3.9.egg/tid/get_data.py", line 791, in parallel_populate_data
    download_res = pool.map(download_and_process, to_download)
  File "/home/kavita/anaconda3/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/kavita/anaconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: The DType <class 'numpy.dtype[float64]'> could not be promoted by <class 'numpy.dtype[datetime64]'>. This means that no common DType exists for the given inputs. For example they cannot be stored in a single array unless the dtype is `object`. The full list of DTypes is: (<class 'numpy.dtype[float64]'>, <class 'numpy.dtype[datetime64]'>)

**Comment by jmccartin** [comment]
Hi, any chance you could provide a little extra context here, and not just a raw error message? System you are running on, etc.

It looks like you might have a library issue - did you follow the exact setup instructions in the README?

**Comment by joywet** [comment]
Hello, Yes I have followed the similar installation procedure as mentioned.
I am using Ubuntu 18.04.6 LTS os and Python 3.9.13 machine.
I am getting this error while vandenberg.py ,would you please brief me what are the changes required to run this project on my system.
I am beginner in GNSS data , can you suggest me where I can get data labels or feature names in rinex files.
